# Setup

In [37]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import mean_absolute_error, mean_squared_error
from IPython.display import display, Math
  
dataset = pd.read_csv('data/basic_sample.csv')

# Exploratory Data Analysis (EDA)

In [14]:
dataset.count()

square_feet    7
price          7
predicted      7
dtype: int64

In [15]:
dataset.head()

   square_feet  price  predicted
0         1500    210        215
1         1800    240        248
2         2200    290        292
3         2400    350        314
4         2600    330        337

In [16]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   square_feet  7 non-null      int64
 1   price        7 non-null      int64
 2   predicted    7 non-null      int64
dtypes: int64(3)
memory usage: 300.0 bytes

In [17]:
dataset.describe()

       square_feet       price   predicted
count     7.000000    7.000000    7.000000
mean   2385.714286  312.857143  312.857143
std     612.178001   69.453650   67.787483
min    1500.000000  210.000000  215.000000
25%    2000.000000  265.000000  270.000000
50%    2400.000000  330.000000  314.000000
75%    2800.000000  360.000000  359.000000
max    3200.000000  400.000000  403.000000

## Pandas & Numpy Exploration

Below examples generate validation needed for a future linear regression model. The error delta, mean absolute error and mean square error (or cost function) are generated and appended to the initial pandas dataframe for analysis.

In [18]:
dataset.price

0    210
1    240
2    290
3    350
4    330
5    370
6    400
Name: price, dtype: int64

In [19]:
type(dataset.price)

pandas.Series

### Single Column Pandas Column to 1D Numpy Array

In [20]:
# Convert a single column to a NumPy array
price_label_array = dataset['price'].to_numpy()

print(price_label_array)
print(type(price_label_array))

[210 240 290 350 330 370 400]
<class 'numpy.ndarray'>

## Mean Absolute Error Exploration

MAE is more forgiving on outliers, specially large ones.

### Math

In [ ]:

# the \frac{1}{n} is to make it easier to handle larger values so its optional for small domain datasets
display(Math(r'MAE = \frac{1}{n} \sum_{i=1}^{n} |y_i - \hat{y}_i|'))

Range dimensions: all positive real numbers. This was defined by this model and data which makes sense.

In [35]:

# Large positive real numbers (greater than some threshold M)
display(Math(r'x \in (M, +\infty), \quad M \gg 0'))

# Or using set notation
display(Math(r'x \in \mathbb{R}^+, \quad x > M, \quad M \gg 0'))

# Bounded large positive reals
display(Math(r'x \in [M, N], \quad M, N \in \mathbb{R}^+, \quad M \gg 0'))

# Using interval notation with infinity
display(Math(r'x \in [M, \infty)'))

### Mean Absolute Error w/Numpy

In [28]:
# y_true = np.array([3, -0.5, 2, 7])
# y_pred = np.array([2.5, 0.0, 2, 8])

# mae = np.mean(np.abs(y_true - y_pred))
# print(f"MAE: {mae}")

y_price_array = dataset['price'].to_numpy()
y_pred_array = dataset['predicted'].to_numpy()
mae_np = np.mean(np.abs(y_price_array - y_pred_array)) 
print(f"MAE: {mae_np}")

MAE: 10.285714285714286

### Mean Absolute Error w/Sklearn

In [39]:
mae_skl = mean_absolute_error(y_price_array, y_pred_array)
print(f"MAE: {mae_skl}")

MAE: 10.285714285714286

### Calculate Error Delta (Residuals)

In [24]:
# Calculate delta: actual - predicted (residuals)
delta = y_price_array - y_pred_array

print(f"Delta (Residuals):\n{delta}")
print(f"\nDelta shape: {delta.shape}")
print(f"Mean delta: {np.mean(delta):.4f}")
print(f"Std delta: {np.std(delta):.4f}")

Delta (Residuals):
[ -5  -8  -2  36  -7 -11  -3]

Delta shape: (7,)
Mean delta: 0.0000
Std delta: 14.9666

## Mean Square Error

### Mean Square Error w/Sklearn

In [40]:
mse_skl = mean_squared_error(y_price_array, y_pred_array)
print(f"MSE: {mse_skl}")

MSE: 224.0

## Append Error Metrics to Dataset Pandas Dataframe

In [25]:
dataset['error'] = delta
print(dataset.head())

   square_feet  price  predicted  error
0         1500    210        215     -5
1         1800    240        248     -8
2         2200    290        292     -2
3         2400    350        314     36
4         2600    330        337     -7

In [26]:
dataset.describe()

       square_feet       price   predicted      error
count     7.000000    7.000000    7.000000   7.000000
mean   2385.714286  312.857143  312.857143   0.000000
std     612.178001   69.453650   67.787483  16.165808
min    1500.000000  210.000000  215.000000 -11.000000
25%    2000.000000  265.000000  270.000000  -7.500000
50%    2400.000000  330.000000  314.000000  -5.000000
75%    2800.000000  360.000000  359.000000  -2.500000
max    3200.000000  400.000000  403.000000  36.000000

In [29]:
# Create a new dataframe with mae_np as a column
new_df = pd.DataFrame({'mae': [mae_np] * len(dataset)})
print(new_df)

         mae
0  10.285714
1  10.285714
2  10.285714
3  10.285714
4  10.285714
5  10.285714
6  10.285714

In [41]:
# Create a new dataframe and append mae_np as a column
df_with_mae = dataset.copy()
df_with_mae['mae_np'] = mae_np
df_with_mae['mae_skl'] = mae_skl
df_with_mae['mse_skl'] = mse_skl
print(df_with_mae)

   square_feet  price  predicted     mae_np    mae_skl  mse_skl
0         1500    210        215  10.285714  10.285714    224.0
1         1800    240        248  10.285714  10.285714    224.0
2         2200    290        292  10.285714  10.285714    224.0
3         2400    350        314  10.285714  10.285714    224.0
4         2600    330        337  10.285714  10.285714    224.0
5         3000    370        381  10.285714  10.285714    224.0
6         3200    400        403  10.285714  10.285714    224.0